name: Update SP500 Data

on:
  workflow_dispatch:

jobs:
  sp500:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run SP500 tracker
        run: python sp500.py