name: Update SP500 Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  sp500:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run SP500 tracker
        run: python sp500.py
      
      - name: Update SP500.png
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add SP500.png

          if git diff --cached --quiet
          then
            echo "No changes to commit"
          else
          git commit -m "update SP500.png"
          git push 
          fi